name: ookla-statcan
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - requests
  - python-dotenv
  - scikit-learn
  - matplotlib
  - notebook
  - jupyterlab
  - pip
  - streamlit